updated plot_pk function
usc-cosmolab/hackspace pull request #20
Opened 2020-02-15 01:11 UTC by annahaynie

2020-02-15 01:31 UTC, syasini requested changes
@annahaynie Thanks, Anna. I think we forgot to return the fig at the end of the plot function.

2020-02-15 01:32 UTC, annahaynie commented
@syasini I thought we decided that the "return fig" at the end was redundant and caused the plot to show twice? I may be misremembering

2020-02-15 02:00 UTC, syasini commented
@annahaynie No, you're absolutely right. It does behave like that in the jupyter notebook, but I think @timothydmorton wanted the function to return an instance of matplotlib. At least that's what's implemented in the current test. Maybe he can clarify this after reviewing the commits.

2020-02-21 07:23 UTC, timothydmorton requested changes

2020-02-21 07:23 UTC, timothydmorton commented on lya/data.py
> +if params is None:
I think you're missing a `data = load_lya_data(filename)` line somewhere at the top of this function that was here before.

2020-02-21 07:23 UTC, timothydmorton commented on lya/data.py
> +from theory import get_theory_pk
this should be `.theory` (or have the first line be `from .theory import get_lcdm_pk, get_theory_pk`)

2020-02-21 07:23 UTC, timothydmorton commented on lya/data.py
> +"""Plot p(k) power spectrum data and theory, with panel for residuals
The indentation of this function is missing.  Indentation matters in python (the whole function should be indented; standard is 4 spaces (your text editor should map the tab key to a four-space indent)

2020-02-21 07:23 UTC, timothydmorton commented on lya/data.py
> +
In this logic branch, we also want to be returning a `fig` instance.  So at the beginning of this, you can start with `fix, ax = plt.subplots(1, 1)` and then do `ax.errorbar`, as it was before.

2020-02-21 07:24 UTC, timothydmorton commented
In the notebook, if you don't want the figure to display twice, you can end the last line of your cell with a `;`-- that will suppress the output.

2020-02-21 23:11 UTC, timothydmorton approved these changes

2020-02-21 23:11 UTC, merged